site_name: BackStack

pages:
  - Home: 'index.md'
  - User Guide:
    - 'Getting Started': 'getting_started.md'
    - 'Linear Back Stack': 'linear_back_stack.md'
    - 'Split Back Stack': 'split_back_stack.md'
    - 'View Creators': 'view_creator.md'
  - About:
    - 'License': 'license.md'
